# Configuration pour API_Commandes
database:
  name: commandesdb
  user: postgres
  password: root  
  host: localhost
  port: 5432
  engine: postgresql

# Configuration RabbitMQ
rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest

# URLs des autres services
services:
  products_api: "http://localhost:8001"
  clients_api: "http://localhost:8002"